package net.anotheria.anodoc.service;

/**
 * File:ModuleStorageFactory
 * Generated by CIPEnhancer V1.0.
 * Factory for the stub.
 * NEVER change generated code if you don't know what you do.
 */

public class ModuleStorageFactory{

	private ModuleStorageFactory() {
	}

	public static final IModuleStorage getModuleStorage(){
//		return new ModuleStorageC();
		return null;
	}
}
