package net.anotheria.anodoc.util;

/**
 * File:CommonModuleStorageException
 * Generated by CIPEnhancer V1.0
 * Base exception class for this service, custom exceptions should derive from it.
 * NEVER change generated code if you don't know what you do.
 */

public class CommonModuleStorageException extends Exception{
	public CommonModuleStorageException(String aMessage){
		super(aMessage);
	}
}
