package net.anotheria.asg.generator.view;

import net.anotheria.asg.generator.Context;
import net.anotheria.asg.generator.FileEntry;
import net.anotheria.asg.generator.GeneratedJSPFile;
import net.anotheria.asg.generator.meta.MetaModule;

public class IndexPageJspMafGenerator extends AbstractJSPGenerator {

	public FileEntry generate(Context context) {
		FileEntry page = new FileEntry(FileEntry.package2path(context.getPackageName(MetaModule.SHARED) + ".jsp"), getIndexPageJspName(),
				generateIndexPage().createFileContent());
		page.setType(".jsp");
		return page;
	}

	public static final String getIndexPageJspName() {
		return "IndexPage";
	}

	public static final String getSharedJspFooterPageName() {
		return getIndexPageJspName() + "Maf.jsp";
	}

	private GeneratedJSPFile generateIndexPage() {
		GeneratedJSPFile jsp = new GeneratedJSPFile();
		startNewJob(jsp);
		jsp.setName(getIndexPageJspName());

		resetIdent();

		append(getBaseJSPHeader());
		
		appendString("<!--  generated by IndexPageJspMafGenerator.generateIndexPage -->");	
		appendString("<html:html>");
		appendString("<head>");
		increaseIdent();
		appendString("<title>" + getIndexPageJspName() + "</title>");
		generatePragmas();
		appendString("<link href=\"" + getCurrentCSSPath("newadmin.css") + "\" rel=\"stylesheet\" type=\"text/css\">");
		decreaseIdent();
		appendString("</head>");
		appendString("<body>");

		appendString("</body>");
		appendString("</html:html>");
		appendString("<!-- / generated by IndexPageJspMafGenerator.generateIndexPage -->");

		append(getBaseJSPFooter());

		return jsp;
	}

}
