package net.anotheria.asg.generator.view;

import java.util.List;

import net.anotheria.asg.generator.Context;
import net.anotheria.asg.generator.FileEntry;
import net.anotheria.asg.generator.GeneratedJSPFile;
import net.anotheria.asg.generator.meta.MetaModule;
import net.anotheria.asg.generator.view.meta.MetaModuleSection;
import net.anotheria.asg.generator.view.meta.MetaSection;
import net.anotheria.asg.generator.view.meta.MetaView;

public class JspMenuGenerator extends AbstractJSPGenerator {

	public FileEntry generate(List<MetaView> views , Context context) {
		
		FileEntry menu = new FileEntry(generateMenu(views, context));
		return menu;
		
	}
	
	public static final String getMenuName(){
		return "Menu";
	}
	
	public static final String getMenuPageName(){
		return getMenuName()+".jsp";
	}
	
	private GeneratedJSPFile generateMenu(List<MetaView> views, Context context){
		GeneratedJSPFile jsp = new GeneratedJSPFile();
		startNewJob(jsp);
		jsp.setName(getMenuName());
		jsp.setPackage(context.getPackageName(MetaModule.SHARED)+".jsp");
		append(getBaseJSPHeader());

		appendString("<!-- dynamic menu -->");
		appendString("<%-- generated by: "+getClass().getName()+"--%>");
		appendString("<ul class=\"menuBar\" id=\"mainMenu\">");
		increaseIdent();
		appendString("<li>");
		increaseIdent();
		appendString("<a class=\"menuButton\" href=\"\" onclick=\"return buttonClick(this);\">System</a>");
		appendString("<ul>");
		increaseIdent();
		appendString("<li><a href=\"\">About</a></li>");
		appendString("<li class=\"menuItemSep\"><div>&nbsp;</div></li>");
		appendString("<li><a href=\"\">Preferences</a></li>");
		appendString("<li class=\"menuItemSep\"><div>&nbsp;</div></li>");
		appendString("<li><a href=\"logout\">Logout</a></li>");
		decreaseIdent();
		appendString("</ul>");
		decreaseIdent();
		appendString("</li>");

		appendString("<li>");
		increaseIdent();
		appendString("<a class=\"menuButton\" href=\"\" onclick=\"return buttonClick(this);\">Modules</a>");
		increaseIdent();
		appendString("<ul>");
		increaseIdent();
		for (MetaView view : views){
			appendString("<li>");
			increaseIdent();
			String viewLink = "";
			if (view.getSections().size()>0){
				MetaSection s = view.getSections().get(0);
				if (s instanceof MetaModuleSection){
					viewLink = StrutsConfigGenerator.getPath(((MetaModuleSection)s).getDocument(), StrutsConfigGenerator.ACTION_SHOW);
					viewLink = "<ano:tslink>"+viewLink+"</ano:tslink>";
				}
			}
			appendString("<a href=\""+viewLink+"\">"+view.getTitle()+"</a>");
			List<MetaSection> sections = view.getSections();
			if (sections.size()>0){
				appendString("<ul>");
				increaseIdent();
				for (MetaSection section : sections){
					String link = "";
					if (section instanceof MetaModuleSection){
						link = StrutsConfigGenerator.getPath(((MetaModuleSection)section).getDocument(), StrutsConfigGenerator.ACTION_SHOW);
						link = "<ano:tslink>"+link+"</ano:tslink>";
					}
					if (section instanceof MetaModuleSection){
						appendString("<li>");
						increaseIdent();
						appendString("<a href=\""+link+"\">"+section.getTitle()+"</a>");
						decreaseIdent();
						appendString("<ul>");
						increaseIdent();
						appendString("<li><a href=\""+link+"\">Show</a></li>");
						link = StrutsConfigGenerator.getPath(((MetaModuleSection)section).getDocument(), StrutsConfigGenerator.ACTION_NEW);
						link = "<ano:tslink>"+link+"</ano:tslink>";
						appendString("<li><a href=\""+link+"\">New</a></li>");
						decreaseIdent();
						appendString("</ul>");
						appendString("</li>");
					}else{
						appendString("<li><a href=\""+link+"\">"+section.getTitle()+"</a></li>");
					}
				}
				decreaseIdent();
				appendString("</ul>");
				
			}
			decreaseIdent();
			appendString("</li>");
		}
		decreaseIdent();
		appendString("</ul>");
		decreaseIdent();
		appendString("</li>");

		
		decreaseIdent();
		appendString("</ul>");
		appendString("<!-- / dynamic menu end-->");

		return jsp;
	}
}
